language: go

dist: xenial

sudo: required

services:
  - docker

cache:
  directories:
  - $GOPATH/pkg/dep

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - sudo mount --make-shared /
  - ci/start-okd-3.11.sh

after_failure:
  - ps aux
  - free
  - ./oc get nodes
  - docker ps -a
  - for log in $(docker ps -qa | xargs); do echo "==========" && docker logs --tail 500 $log; done

script:
  - make test
